### ISSUE TITLE
[Bug]: Reveal issues 

### ISSUE THREAD

**Issue by blizzyenterprises** [metaplex-foundation/sugar#328]
### Issue description

1. sugar reveal (on devnet)
2. return error "main" panicked
3. note that this is mid-mint, attempting to reveal partially minted collection on devnet

### Relevant log output

```shell
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', src\reveal\process.rs:323:25
```

### Priority this issue should have

Medium (should be fixed soon)

**Comment by samuelvanderwaal** [comment]
@blizzyenterprises do you have a collection item in your cache file? (Will be a key of "-1".)

**Comment by blizzyenterprises** [comment]
I see the fix, thank you @samuelvanderwaal @stegaBOB

**Comment by stegaBOB** [comment]
All the credit for the fix goes to @samuelvanderwaal. I just click buttons 😆

**Comment by blizzyenterprises** [comment]
Now it's throwing a new error, 

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', \sugar\src\reveal\process.rs:203:43

**Comment by samuelvanderwaal** [comment]
> Now it's throwing a new error,
> 
> thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', \sugar\src\reveal\process.rs:203:43

Can you post your cache file here or send it to me on Discord or email it to me at sam@metaplex.com?

**Comment by blizzyenterprises** [comment]
testing this on devnet
[cache.txt](https://github.com/metaplex-foundation/sugar/files/9390062/cache.txt)

i can get them to reveal using metaboss method, but "sugar reveal" is causing that issue above

**Comment by samuelvanderwaal** [comment]
> testing this on devnet [cache.txt](https://github.com/metaplex-foundation/sugar/files/9390062/cache.txt)
> 
> i can get them to reveal using metaboss method, but "sugar reveal" is causing that "unwrap" issue above
> 
> Once i get more experience i might be able to offer solutions instead of issues ;)

There's only the collections item in your cache file, no other ones. Did you run `sugar upload`?

**Comment by blizzyenterprises** [comment]
As it is a hidden collection the only upload was the hidden.png and hidden.json

**Comment by blizzyenterprises** [comment]
i have the collection minting on mainnet now, and using metaboss to reveal, but i feel like the reveal functionality of sugar should be working correctly, is it an issue because i have a "hidden" collection and they weren't loaded to CMID from the beginning?

**Comment by samuelvanderwaal** [comment]
This is just a misunderstanding of how Sugar handles `reveal`. If you want to use `sugar reveal` you still need to use `upload` to create all the external links for the assets. This does not upload the assets on-chain to Solana, it just uses the third-party storage method you choose (aws, bundlr, nft.storage, shdw) to upload and store the external metadata and images. Otherwise, Sugar doesn't know how to update your NFTs as it uses the values in the cache file for the `reveal` step.

**Comment by blizzyenterprises** [comment]
Interesting.

While this is minting can i upload the images/jsons through the sugar commands, and then use reveal?

**Comment by blizzyenterprises** [comment]
FYI guys, the main issue was this....the only NFTs I had uploaded to the CM were the hidden.png/hidden.json, the CM didn't know what to attempt to even reveal.  you were right @samuelvanderwaal, even though i followed someone that seemed to know what they were doing, it didn't work as they described.  I apologize for wasting the time, but I'm glad it failed so I could learn exactly how to fix it. 💯
